# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'QSApiAnalytics' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'QSNetRequest'
  pod 'QSIpLocation'
  pod 'WCDBSwift'
  pod 'QSModelConvert'

end

target 'QSApiAnalyticsWatch Watch App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'QSNetRequest'
  pod 'QSIpLocation'
  pod 'QSModelConvert'

end
